language: python
python:
  - "3.7"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - git config --global http.sslverify false
  - export GIT_SSL_NO_VERIFY=true

addons:
  apt:
    packages:
 #   - libwebkitgtk-dev
 #   - libjpeg-dev
 #   - libtiff-dev
    - libgtk-3-dev
 #   - libsdl1.2-dev
 #   - libgstreamer-plugins-base0.10-dev
 #   - freeglut3
 #   - freeglut3-dev
 #   - libnotify-dev

 # command to install dependencies
install:
  - pip install -r requirements.txt
# command to run
script: python devsimpy.py