language: python
python:
  - "3.7"

addons:
  apt:
    packages:
    - libwebkitgtk-dev
    - libjpeg-dev
    - libtiff-dev
    - libgtk2.0-dev
    - libsdl1.2-dev
    - libgstreamer-plugins-base0.10-dev
    - freeglut3
    - freeglut3-dev
    - libnotify-dev

 # command to install dependencies
install:
  - pip install -r requirements.txt
# command to run
script: python devsimpy.py